services:
  app-be:
    build:
      # use project root as build context so we can access all files
      context: ../
      args:
        - env=${APP_ENV}
      dockerfile: docker/be.dockerfile
    image: laravel/php
    container_name: app-be
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      - ${APP_PORT}:9000
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./../src/be/:/var/www
      - ./php/dev/php.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - app-db-php
    links:
      - app-db-php
    networks:
      - app-be-network

  app-be-nginx:
    image: nginx:alpine
    container_name: app-be-nginx
    restart: ${DOCKER_RESTART_POLICY}
    tty: true
    ports:
      - ${NGINX_PORT}:80
      #- ${NGINX_SSL_PORT}:443
    volumes:
      - ./../src/be/:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app-be-network

  app-db:
    image: postgres:17-alpine
    container_name: app-db-php
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - app-dbdata:/var/lib/postgresql/data/
    networks:
      - app-be-network

  app-db-admin:
    image: dpage/pgadmin4
    container_name: app-db-admin
    restart: ${DOCKER_RESTART_POLICY}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_USERNAME}
      - PGADMIN_DEFAULT_PASSWORD=${DB_ADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - ${DB_ADMIN_PORT}:80
    depends_on:
      - app-db-php
    networks:
      - app-be-network

  app-redis:
    image: 'redis:alpine'
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      - '${FORWARD_REDIS_PORT:-6380}:6379'
    volumes:
      - 'app-redisdata:/data'
    networks:
      - app-be-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  app-fe:
    # Use a custom image for nuxt
    build:
      context: ../
      dockerfile: docker/fe.dockerfile
    container_name: app-fe
    restart: always
    ports:
      - ${APP_FE_PORT}:5173
    volumes:
      - ./../src/fe/:/app
      - /app/node_modules/
    environment:
      - HOST=0.0.0.0

# Docker Networks
networks:
  app-be-network:
    driver: bridge

# Volumes
volumes:
  app-dbdata:
    driver: local
  app-redisdata:
    driver: local