/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    FlycomLoadingContainer: typeof import('./src/components/elements/FlycomLoadingContainer.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
